"""empty message

Revision ID: 0ad56c215355
Revises: 5cbb2acb1a4c
Create Date: 2022-04-07 12:18:04.976797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad56c215355'
down_revision = '5cbb2acb1a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_comments_post_id_fkey', 'post_comments', type_='foreignkey')
    op.create_foreign_key(None, 'post_comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.create_foreign_key('post_comments_post_id_fkey', 'post_comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
