"""empty message

Revision ID: 2f174f31e319
Revises: 4ab6d9289153
Create Date: 2022-04-07 12:13:54.413099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f174f31e319'
down_revision = '4ab6d9289153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_teams_team_id_fkey', 'players_teams', type_='foreignkey')
    op.drop_constraint('players_teams_player_id_fkey', 'players_teams', type_='foreignkey')
    op.create_foreign_key(None, 'players_teams', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'players_teams', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players_teams', type_='foreignkey')
    op.drop_constraint(None, 'players_teams', type_='foreignkey')
    op.create_foreign_key('players_teams_player_id_fkey', 'players_teams', 'players', ['player_id'], ['id'])
    op.create_foreign_key('players_teams_team_id_fkey', 'players_teams', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
