"""empty message

Revision ID: 5cbb2acb1a4c
Revises: 2f174f31e319
Create Date: 2022-04-07 12:16:15.654502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbb2acb1a4c'
down_revision = '2f174f31e319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_comments_team_id_fkey', 'team_comments', type_='foreignkey')
    op.create_foreign_key(None, 'team_comments', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_comments', type_='foreignkey')
    op.create_foreign_key('team_comments_team_id_fkey', 'team_comments', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
